<?php

namespace AppBundle\Repository;

/**
 * AgujaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgujaRepository extends \Doctrine\ORM\EntityRepository
{
}
