<?php

namespace AppBundle\Repository;

/**
 * GuanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuanteRepository extends \Doctrine\ORM\EntityRepository
{
}
