<?php

namespace AppBundle\Repository;

/**
 * JeringaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeringaRepository extends \Doctrine\ORM\EntityRepository
{
}
