<?php

namespace AppBundle\Repository;

/**
 * PrincipioActivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrincipioActivoRepository extends \Doctrine\ORM\EntityRepository
{
}
