<?php

namespace AppBundle\Repository;

/**
 * TorniqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorniqueteRepository extends \Doctrine\ORM\EntityRepository
{
}
