guante_index:
    path:     /
    defaults: { _controller: "AppBundle:Guante:index" }
    methods:  GET

guante_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Guante:show" }
    methods:  GET

guante_new:
    path:     /new
    defaults: { _controller: "AppBundle:Guante:new" }
    methods:  [GET, POST]

guante_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Guante:edit" }
    methods:  [GET, POST]

guante_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Guante:delete" }
    methods:  DELETE
