jeringa_index:
    path:     /
    defaults: { _controller: "AppBundle:Jeringa:index" }
    methods:  GET

jeringa_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Jeringa:show" }
    methods:  GET

jeringa_new:
    path:     /new
    defaults: { _controller: "AppBundle:Jeringa:new" }
    methods:  [GET, POST]

jeringa_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Jeringa:edit" }
    methods:  [GET, POST]

jeringa_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Jeringa:delete" }
    methods:  DELETE
