principioactivo_index:
    path:     /
    defaults: { _controller: "AppBundle:PrincipioActivo:index" }
    methods:  GET

principioactivo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PrincipioActivo:show" }
    methods:  GET

principioactivo_new:
    path:     /new
    defaults: { _controller: "AppBundle:PrincipioActivo:new" }
    methods:  [GET, POST]

principioactivo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PrincipioActivo:edit" }
    methods:  [GET, POST]

principioactivo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PrincipioActivo:delete" }
    methods:  DELETE
