torniquete_index:
    path:     /
    defaults: { _controller: "AppBundle:Torniquete:index" }
    methods:  GET

torniquete_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Torniquete:show" }
    methods:  GET

torniquete_new:
    path:     /new
    defaults: { _controller: "AppBundle:Torniquete:new" }
    methods:  [GET, POST]

torniquete_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Torniquete:edit" }
    methods:  [GET, POST]

torniquete_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Torniquete:delete" }
    methods:  DELETE
