index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

app_aguja:
    resource: "@AppBundle/Resources/config/routing/aguja.yml"
    prefix:   /aguja

app_comprimido:
    resource: "@AppBundle/Resources/config/routing/comprimido.yml"
    prefix:   /comprimido

app_guante:
    resource: "@AppBundle/Resources/config/routing/guante.yml"
    prefix:   /guante

app_jeringa:
    resource: "@AppBundle/Resources/config/routing/jeringa.yml"
    prefix:   /jeringa

app_marca:
    resource: "@AppBundle/Resources/config/routing/marca.yml"
    prefix:   /marca

app_principioactivo:
    resource: "@AppBundle/Resources/config/routing/principioactivo.yml"
    prefix:   /principioactivo

app_torniquete:
    resource: "@AppBundle/Resources/config/routing/torniquete.yml"
    prefix:   /torniquete
